### ISSUE TITLE
Give a timeout limit when acquiring lock

### ISSUE THREAD

**Issue by arthurhsu** [WICG/web-locks#41]
It would be nice to specify a timeout for lock (i.e. how long should this lock be there). A worker thread can have bugs looping forever without releasing locks, and there will be no way to re-gain the lock.

This can also promote shorter locks if default is a reasonable amount of time instead of infinite.

**Comment by ralphch0** [comment]
This is the motivation behind the "steal" feature. The difficulties with both of these features is that it's not easy to interrupt running code that's holding the lock, unless we introduce some kind of page crash/reload when the lock is stolen (or expires).

**Comment by inexorabletash** [comment]
Closing this pending feedback that "steal" is insufficient here. I'd like to avoid introducing another mechanism.
