### ISSUE TITLE
calling functions and resolving promises from parallel queues

### ISSUE THREAD

**Issue by devsnek** [WICG/web-locks#47]
This spec says in a lot of places to operate on the JS VM from steps being run in parallel queues, which I don't think is possible.

I assume that what should be happening in place of this is steps saying to queue tasks operating on the JS VM instead, but since some of these things happen in loops I'm not totally sure if it's safe to make this assumption.

cc @domenic

**Comment by domenic** [comment]
See third paragraph in https://www.w3.org/2001/tag/doc/promises-guide#resolve-promise.

But also see https://github.com/w3ctag/promises-guide/issues/52.

**Comment by inexorabletash** [comment]
Thanks! 

In [process the lock request queue](https://wicg.github.io/web-locks/#process-the-lock-request-queue) where the callback is invoked should definitely "queue a task".

I didn't spot any others, so please point them out.

**Comment by inexorabletash** [comment]
Ah, and in [request a lock](https://wicg.github.io/web-locks/#algorithm-request-lock), a similar "invoking" phrase.

**Comment by inexorabletash** [comment]
PR up at https://github.com/WICG/web-locks/pull/48 - @devsnek can you take a look?
