### ISSUE TITLE
This api not work in Chrome 69

### ISSUE THREAD

**Issue by hamedmoody** [WICG/web-locks#49]
Hi
My Chrome is 69. But Weblock show error:
Uncaught TypeError: Cannot read property 'request' of undefined

MyCode is:
```
navigator.locks.request('my_resource', async lock => {
// The lock has been acquired.
// await do_something();
// await do_something_else();
// Now the lock will be released.
});
```

**Comment by inexorabletash** [comment]
You should file an issue against Chrome using https://new.crbug.com

However, I suspect you're trying from a non-secure origin, where the `navigator.locks` property would not be present. Try from a console from https://example.com/ (vs. http://example.com/)

**Comment by inexorabletash** [comment]
Closing because this is not a spec issue.
