### ISSUE TITLE
Polyfill status?

### ISSUE THREAD

**Issue by dylans** [WICG/web-locks#50]
What's the status of the web locks polyfill? It looks like it was [quietly removed from master](https://github.com/WICG/web-locks/commit/b7bc471f75c51b6f2e43788a1cf97c1e35a3430e) without an issue or PR. Could you please let me know if there are there plans to create a new polyfill or is the spec in a state of significant rewrite currently or something else? Thanks!

**Comment by inexorabletash** [comment]
A good polyfill is not possible, hence the need for such a primitive. The earlier one was mostly a sketch of the API (which has changed) and demonstration of where it fails.

Chrome has shipped the feature.

**Comment by wmhilton** [comment]
What about a bad polyfill?

**Comment by inexorabletash** [comment]
You could write one, but shipping something known broken is not in scope for this repo.

**Comment by piotrblasiak** [comment]
Isn't it possible to write a good polyfill using IndexedDb? What would be missing/broken?

**Comment by justinbmeyer** [comment]
I'm working on a bad polyfill.  One I'd like to make work without `SharedWorker`.  I just need the basic behavior.

My plan is to use localStorage as sort of a mutex. For disconnections, I'm planning on running some sort of keep-alive where the tab with the lock has to update localStorge every second or so; otherwise, the tab is considered disconnected.

Is this crazy?  Any advice would be great. Thanks!

**Comment by justinbmeyer** [comment]
Seems like you can't rely on localStorage:

https://html.spec.whatwg.org/multipage/webstorage.html#the-localstorage-attribute


>  The localStorage getter provides access to shared state. This specification does not define the interaction with other browsing contexts in a multiprocess user agent, and authors are encouraged to assume that there is no locking mechanism. A site could, for instance, try to read the value of a key, increment its value, then write it back out, using the new value as a unique identifier for the session; if the site does this twice in two different browser windows at the same time, it might end up using the same "unique" identifier for both sessions, with potentially disastrous effects.

**Comment by justinbmeyer** [comment]
I was able to get it working (at least in Safari).  Here's the repo: https://github.com/bitovi/web-locks-polyfill.  It only supports the default use case.

**Comment by aermin** [comment]
I developed a more complete polyfill  with localstorage, support all the mainstream browsers usage，Here's the repo: https://github.com/aermin/web-locks .

- implement features according to Web Locks API Specification

- implement the unit tests according to the test case provide from Specification 

- implement all the features of Web Locks API
