### ISSUE TITLE
LockGrantedCallback IDL looks wrong

### ISSUE THREAD

**Issue by bzbarsky** [WICG/web-locks#51]
The IDL says:

    callback LockGrantedCallback = Promise<any> (Lock lock);

but https://wicg.github.io/web-locks/#algorithm-request-lock step 6.1.1 passes `null` as  the argument, which is not a valid `Lock` value.  Presumably this callback should take `Lock?`.

**Comment by inexorabletash** [comment]
Whoops, yep. Fixed. WPT change coming.
