### ISSUE TITLE
Note on calling callback doesn't make sense

### ISSUE THREAD

**Issue by bzbarsky** [WICG/web-locks#53]
https://wicg.github.io/web-locks/#algorithm-request-lock step 6.1.1 has a note that says

> Note that r could be a regular completion, an abrupt completion, or an unresolved Promise.

but assuming "invoking callback" means https://heycam.github.io/webidl/#es-invoking-callback-functions the only thing _r_ can be is a Promise.   That's because https://heycam.github.io/webidl/#es-invoking-callback-functions step 13 will convert regular completions to promises and step 14.5 will convert abrupt completions to promises.

That said, the promise could be resolved or not; there's nothing that forces it to be unresolved.

**Comment by bzbarsky** [comment]
https://wicg.github.io/web-locks/#algorithm-process-request step 3.1.10.1 has the same issue.

**Comment by inexorabletash** [comment]
Nice, I didn't realize WebIDL handled this automagically. I can just remove the notes.
