### ISSUE TITLE
Migration to WebApps WG: Implementor interest?

### ISSUE THREAD

**Issue by LJWatson** [WICG/web-locks#55]
This specification has been proposed for migration to the [WebApps WG](https://w3c.github.io/charter-drafts/webapps-2019) (which is expected to partly replace the WebPlat WG). For this to happen, we need expressions of interest/intent to commit from at least two implementors.

Please let us know if you plan to implement this specification, or if you can point to any publicly documented expressions of interest from implementors.

The draft WebApps charter will go to the Advisory Committee (AC) within the next two or three weeks, so quick responses may make the difference.

@Chaals @marcoscaceres

**Comment by inexorabletash** [comment]
@asutherland - any comment here?

FWIW, happy to bring on additional editor(s) here.

**Comment by marcoscaceres** [comment]
It sounds like Mozilla is interested in prototyping, based on https://github.com/mozilla/standards-positions/issues/64#issuecomment-521786572 

We will have to check if this falls within scope of the WebApps WG charter... we could take it up during TPAC.

**Comment by inexorabletash** [comment]
If we took this up at TPAC I missed it. :( 

I'm still looking forward to this being adopted by WebApps if/when appropriate.

**Comment by marcoscaceres** [comment]
@inexorabletash should we kick off an "[intent to migrate](https://github.com/WICG/admin/blob/gh-pages/intent-to-migrate.md)"? We need to fill out that template. In the meantime, the WebAppsWG chairs can see what we need to do to adopt it. 

I'm still unsure if we have started implementing on the Gecko side... I've not see any "intent to prototype" sent out. @asutherland, do you have any updates?

**Comment by marcoscaceres** [comment]
@othermaciej, do you have opinion from the WebKit side about this particular spec being adopted by WebApps for standardization? mozilla/standards-positions#64 was leaning towards "worth prototyping" - but with some issues were raised.

**Comment by othermaciej** [comment]
We've had some internal discussion but no final conclusion yet. Cc @hober to collect and summarize feedback.

**Comment by asutherland** [comment]
@marcoscaceres In consultation with Firefox Product, the tentative plan to implement web-locks was deferred.  I'll update the Mozilla standards position when we pick that back up (ideally, during 2020H1).

**Comment by bathos** [comment]
This has been a very valuable API for us. We use a hacky, “not the real thing but _usually_ doesn’t cause bugs” pseudo-polyfill for FF and Safari. It would be really great to hear news on whether this will get traction outside Chrome/Edge.

Also v anecdotal but if it’s interesting to hear dev feedback from people using this API in production:
- at some point, we have actually needed every feature exposed here
- yet at no point has it ever seemed anything was missing
- and it is an absolute pleasure to use

**Comment by marcoscaceres** [comment]
As the WebApps WG charter renewal process is literally happening right now, this is the last chance to get this included if folks really want it. Again, it needs support from at least one more potential implementer to be included.

**Comment by marcoscaceres** [comment]
Ok, I've requested it be added as a possible deliverable:

https://github.com/w3c/webappswg/pull/70 - just need to check if it's ok to add at this stage.

@othermaciej, @hober, just a heads up in case of any objection.

**Comment by marcoscaceres** [comment]
Ok, added as something we can take in WebAppsWG. Please feel free to close this.
