### ISSUE TITLE
Lock request queues are never initialized

### ISSUE THREAD

**Issue by saschanaz** [WICG/web-locks#68]
https://wicg.github.io/web-locks/#algorithm-request-lock

> 2. Enqueue the following steps to the lock task queue:
>     1. Let queueMap be origin’s lock request queue map.
>     2. Let queue be queueMap[name].

But nothing actually set `queueMap[name]`, so `queue` is always nonexistent.

**Comment by inexorabletash** [comment]
Good catch. 

There are four instances of _"Let queue be queueMap[name]"_ - we can either:

* add a preceding step: _"If queueMap[name] does not exist, then set queueMap[name] to a new lock request queue."_; or
* add a new algorithm for "get the lock request queue from a lock request queue map" that populates and returns it.

@pwnall - Any preferences?

**Comment by pwnall** [comment]
I prefer the algorithm approach. And this happens to match the PR you have up. :+1:
