### ISSUE TITLE
`callback` is not defined in "process the lock request queue queue"

### ISSUE THREAD

**Issue by saschanaz** [WICG/web-locks#69]
https://wicg.github.io/web-locks/#process-the-lock-request-queue

> 10. Enqueue the following steps on callback’s relevant settings object's responsible event loop:
>     1. Let r be the result of invoking callback with a new Lock object associated with lock as the only argument.
>     2. Resolve waiting with r.

But there is no variable named `callback` in this algorithm. I guess each request needs to store its callback in it.

**Comment by inexorabletash** [comment]
Yep - likely a refactor didn't capture that.
