### ISSUE TITLE
Checking grantability before enqueuing is invalid

### ISSUE THREAD

**Issue by saschanaz** [WICG/web-locks#70]
https://wicg.github.io/web-locks/#lock-request-grantable

>No lock request in queue earlier than request exists.

This can't be done before enqueuing, but in https://wicg.github.io/web-locks/#algorithm-request-lock:

>     1. If ifAvailable is true and request is not grantable, then enqueue the following steps on callback’s relevant settings object's responsible event loop:
>         1. Let r be the result of invoking callback with null as the only argument.
>         2. Resolve promise with r and abort these steps.
>     2. Enqueue request in queue.

I think it should check whether it's in the queue or not (or define "earlier than" better?)

**Comment by inexorabletash** [comment]
I think that probably needs to be expanded to:

* If request is in queue, then request is the first item in queue.
* If request is not in queue, then queue is empty.

Or alternately:

* Queue is empty, or request is the first item in queue.

Thoughts? cc: @pwnall
