### ISSUE TITLE
What should happen when accessing lock manager on a non-fully-active document?

### ISSUE THREAD

**Issue by saschanaz** [WICG/web-locks#78]
```js
const iframe = document.createElement("iframe");
document.body.append(iframe);
const n = iframe.contentWindow.navigator;
iframe.remove();
n.locks // what do we want here?
```

**Comment by saschanaz** [comment]
The Chrome implementation interestingly silently returns nothing from the methods.

```js
n.locks.request("foo", () => {}); // returns `undefined` instead of a Promise
n.locks.query(); // same
```

Should it instead throw?

**Comment by inexorabletash** [comment]
I suspect both specs and implementations are wildly underspecified/tested here across the platform.

IMHO, I'm happy for the spec to do whatever is most common here, and we can update the Chrome impl. Also, ideally, we'd have somewhere (Infra? WebIDL? dunno) that gives guidance on how APIs should behave in these cases. Maybe even idlharness should be testing these?

Anyway, for web-locks, spec PRs & WPT PRs are very welcome.

**Comment by saschanaz** [comment]
@marcoscaceres has recently been quite active on this topic. Hi Marcos, what's your expected behavior here? 👀

**Comment by marcoscaceres** [comment]
Coincidently, the following guidance just got merged into the TAG design guidelines:
https://w3ctag.github.io/design-principles/#support-non-fully-active

(it's what I've been following, with some guidance from @rakina)

I've not looked at this API in any depth - but I'd suggest starting there. It may be you need to simply return a promise rejected with an `InvalidStateError`.

**Comment by inexorabletash** [comment]
To the specific question, I think we'd want:

* `navigator.locks` should still return a `LockManager` 
* The `request()` and `query()` methods should throw (reject).

Thoughts?

Also... while [full active](https://html.spec.whatwg.org/multipage/browsers.html#fully-active) is defined for documents, is there an easy incantation for Workers?

**Comment by inexorabletash** [comment]
FYI, c/o @domenic  https://github.com/whatwg/html/pull/6379

**Comment by asutherland** [comment]
> Also... while [full active](https://html.spec.whatwg.org/multipage/browsers.html#fully-active) is defined for documents, is there an easy incantation for Workers?

I think for workers there are potentially 2 lifecycle-y things?
- The main lifecycle thing for workers is [close a worker](https://html.spec.whatwg.org/multipage/workers.html#close-a-worker) which sets the workerGlobal's [closing](https://html.spec.whatwg.org/multipage/workers.html#dom-workerglobalscope-closing) flag.  Maybe it makes sense that web locks stop working after calling `self.close()` since the worker's event loop task queues have gone away and your request() can never succeed.  So the verbiage might be `closing flag is false`.
- For ServiceWorkers there's the situation I mentioned in https://github.com/WICG/web-locks/issues/24#issuecomment-521784300 where there are [no pending events](https://w3c.github.io/ServiceWorker/#service-worker-has-no-pending-events).  This would involve new incantations in general.

**Comment by inexorabletash** [comment]
I guess I was wondering what happens in a worker when the owning document goes into BFCache or is in a detached iframe. Does the worker get closed?

**Comment by asutherland** [comment]
[The Worker's lifetime](https://html.spec.whatwg.org/multipage/workers.html#the-worker's-lifetime) covers the general states and the [processing model covers when to suspend](https://html.spec.whatwg.org/multipage/workers.html#worker-processing-model:protected-worker) which is on transition from "active needed worker" to "permissible worker".  The processing model also covers "closing orphan workers".  And then there's just explicit termination and explicit `self.close()`.

Speaking from the hip, detached iframe will terminate the worker, bfcache could potentially suspend, but I am absolutely not up-to-date on changes made to specs resulting from standardization of bfcache, just generally aware of Firefox's implementation ramifications related to bfcache.  I will edit this paragraph as I inevitably and proven to be wrong in ways big and small as my saying this compels people to reply with (more) correct answers.
